# Generated by Django 3.2.3 on 2021-05-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='member',
            name='trello_picture',
            field=models.URLField(max_length=250),
        ),
    ]
