# Generated by Django 3.2.3 on 2021-05-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_member_role',
            name='role',
            field=models.CharField(choices=[('member', 'MEMBER')], default='member', max_length=100),
        ),
    ]
